# Generated by Django 5.0.6 on 2024-05-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventor', models.TextField()),
                ('schoolnamegrade', models.TextField()),
                ('sig', models.TextField()),
                ('date', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StepOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('identify_problems', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='recordofinvention',
            name='name_of_invention',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='recordofinvention',
            name='problem_it_solves',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='StatementOfOriginality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('inventors', models.ManyToManyField(related_name='statement_of_originality', to='website.inventor')),
            ],
        ),
    ]
