# Generated by Django 5.0.6 on 2024-05-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_inventor_stepone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('name1', models.TextField()),
                ('name2', models.TextField()),
                ('name3', models.TextField()),
                ('name4', models.TextField()),
                ('age1', models.TextField()),
                ('age2', models.TextField()),
                ('age3', models.TextField()),
                ('age4', models.TextField()),
                ('comment1', models.TextField()),
                ('comment2', models.TextField()),
                ('comment3', models.TextField()),
                ('comment4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StepTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('problem_title', models.TextField()),
                ('problem_description', models.TextField()),
                ('describe_problem', models.TextField()),
                ('specific_solution', models.TextField()),
                ('problems', models.ManyToManyField(related_name='step_two', to='website.problem')),
            ],
        ),
    ]
