# Generated by Django 5.0.6 on 2024-05-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_problem_steptwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='steptwo',
            name='define_problem',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='steptwo',
            name='desired_solution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='steptwo',
            name='selected_problem',
            field=models.TextField(blank=True),
        ),
    ]
