# Generated by Django 5.0.6 on 2024-05-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_steptwo_define_problem_steptwo_desired_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='steptwo',
            name='selected_problem',
            field=models.TextField(blank=True, null=True),
        ),
    ]
