# Generated by Django 5.0.6 on 2024-05-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_steptwo_define_problem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepEight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('naming', models.TextField(blank=True, null=True)),
                ('where_to_buy', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StepFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('talk_to_expert', models.TextField(blank=True, null=True)),
                ('other_information', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StepFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StepSeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('testing', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StepSix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('arrange_material', models.TextField(blank=True, null=True)),
                ('prototype', models.BinaryField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StepThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('research', models.TextField(blank=True, null=True)),
                ('sources', models.TextField(blank=True, null=True)),
                ('difference', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='steptwo',
            name='describe_problem',
        ),
        migrations.RemoveField(
            model_name='steptwo',
            name='specific_solution',
        ),
    ]
