# Generated by Django 5.0.6 on 2024-05-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_billinginfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField()),
                ('teamId', models.IntegerField()),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('comment', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='steptwo',
            name='problems',
        ),
        migrations.RemoveField(
            model_name='steptwo',
            name='problem_description',
        ),
        migrations.RemoveField(
            model_name='steptwo',
            name='problem_title',
        ),
        migrations.AlterField(
            model_name='stepone',
            name='identify_problems',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
