# Generated by Django 5.0.6 on 2024-05-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_person_remove_steptwo_problems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True),
        ),
    ]
