# Generated by Django 5.0.6 on 2024-05-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_issue_expert_credentials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='expert_credentials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='expert_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
