# Generated by Django 5.0.6 on 2024-06-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
