# Generated by Django 5.0.6 on 2024-06-01 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_alter_customer_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statementoforiginality',
            name='inventors',
        ),
        migrations.AddField(
            model_name='statementoforiginality',
            name='date',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statementoforiginality',
            name='invetor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statementoforiginality',
            name='schoolnamegrade',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statementoforiginality',
            name='sign',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
