# Generated by Django 5.0.6 on 2024-06-01 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_remove_statementoforiginality_inventors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statementoforiginality',
            old_name='invetor',
            new_name='inventor',
        ),
    ]
