# Generated by Django 5.0.6 on 2024-06-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_rename_invetor_statementoforiginality_inventor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventor',
        ),
    ]
