# Generated by Django 5.0.6 on 2024-06-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_alter_person_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepone',
            name='problems',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
